### ISSUE TITLE
Uncaught StopIteration


### ISSUE THREAD

**Issue by peter-shr** [gacarrillor/AutoFields#4]
Steps to reproduce
 1. First - Create Autofield Timestamp
 2. Second - new point
 3. Third - save Layer and Error

```
Traceback (most recent call last):
  File "C:/Users/USER/.qgis2/python/plugins\AutoFields\EventManager.py", line 185, in providerExpressionBasedUpdate
    self.expressionBasedUpdate( layer, dictProperties, feature.id() )
  File "C:/Users/USER/.qgis2/python/plugins\AutoFields\EventManager.py", line 244, in expressionBasedUpdate
    feature = layer.getFeatures( QgsFeatureRequest( featureId ) ).next()
StopIteration

```
AutoFields 0.5.1, QGIS 2.14.20-Essen on Windows 10

**Comment by gacarrillor** [comment]
Thanks for the report.

I couldn't reproduce this in AutoFields 0.5.1, QGIS 2.14.12 on Linux.
I'll give it a try on Windows when I can.
