### ISSUE TITLE
Migrate AutoFields to QGIS v3.0+

### ISSUE THREAD

**Issue by HBConcepts** [gacarrillor/AutoFields#5]
Migrate AutoFields to QGIS v3.0+. 

Currently, trying to install AutoFields 0.5.1 from Zip to QGIS 3.0.2 leads to:

```
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 336, in startPlugin
   plugins[packageName] = package.classFactory(iface)
AttributeError: module 'AutoFields' has no attribute 'classFactory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "", line 1, in 
  File "C:/OSGEO4~1/apps/qgis/./python\pyplugin_installer\installer.py", line 586, in installFromZipFile
    if startPlugin(pluginName):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 338, in startPlugin
    _unloadPluginModules(packageName)
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 405, in _unloadPluginModules
    mods = _plugin_modules[packageName]
KeyError: 'AutoFields'
```

**Comment by gacarrillor** [comment]
What exactly would you expect from AutoFields that you cannot get from configuring Default Values in QGIS 3?

![default_values](https://user-images.githubusercontent.com/652785/39675159-c9aa93aa-511c-11e8-8d6d-a4cc14cc5332.png)

I'd like to know what would be your use case, perhaps it's worth the effort.

Regards, 

Germán

**Comment by HBConcepts** [comment]
Hello Germán,
                Actually, I didn’t know about the default values, and that they could be applied on update. With that in mind, AutoFields becomes redundant for my use case. You can close the issue.

Thank you for all of the work you put in!

**Comment by gacarrillor** [comment]
Great!
