### ISSUE TITLE
ascii

### ISSUE THREAD

**Issue by GeoMapLab** [gacarrillor/AutoFields#7]
1. Trying to install a plugin through the QGIS interface
2. The plugin is downloaded but an error message appears at the validation stage: "python said: ascii"
https://1drv.ms/u/s!Alk-hpLFKlPIgecgn1s7sEqgxPj_BA
Windows 7 32 bit, QGIS 2.18.17

**Comment by gacarrillor** [comment]
Thanks for the report. The error message is a bit unclear, but I'll check that out soon to see if it can be reproduced and fixed. Stay tuned.

**Comment by Dosperanso** [comment]
Username - russian symbols.
More info about this issue:

Не удалось загрузить модуль AutoFields из-за ошибки при вызове его метода classFactory() 

UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-21: ordinal not in range(128) 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/�������������/.qgis2/python/plugins\AutoFields\__init__.py", line 42, in classFactory
    return AutoFields( iface )
  File "C:/Users/�������������/.qgis2/python/plugins\AutoFields\AutoFields.py", line 45, in __init__
    self.installTranslator()
  File "C:/Users/�������������/.qgis2/python/plugins\AutoFields\AutoFields.py", line 194, in installTranslator
    userPluginPath = os.path.join( os.path.dirname( str( QgsApplication.qgisUserDbFilePath() ) ), "python/plugins/AutoFields" )
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-21: ordinal not in range(128)

Версия Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] 
Версия: 2.18.27 Las Palmas, 913411074b

**Comment by Dosperanso** [comment]
A temporary solution to the problem is:
In file "C:/Users/_Username_/.qgis2/python/plugins\AutoFields\AutoFields.py" replace this line 
"userPluginPath = os.path.join( os.path.dirname( str( QgsApplication.qgisUserDbFilePath() ) ), "python/plugins/AutoFields" )" 
with
userPluginPath = "C:/Users/Администратор/.qgis2/python/plugins/AutoFields"
where is "Администратор" - Username
